
export const API_ENDPOINTS = {
  AUTH: {
    REGISTER: "/auth/register",
    LOGIN: "/auth/login",
    REFRESH: "/auth/refresh",
    LOGOUT: "/auth/logout",
    GOOGLE_LOGIN: "/auth/google",
  },
  USERS: {
    ME: "/users/me",
    BY_ID: (id: string) => `/users/${id}`,
    PASSWORD: "/users/me/password",
  },
  GROUPS: {
    BASE: "/groups",
    BY_ID: (id: string) => `/groups/${id}`,
    CHILDREN: (id: string) => `/groups/${id}/children`,
    TREE: "/groups/tree",
    BREADCRUMB: (id: string) => `/groups/${id}/breadcrumb`,
    STATS: (id: string) => `/groups/${id}/stats`,
    MOVE: (id: string) => `/groups/${id}/move`,
    REORDER: (id: string) => `/groups/${id}/reorder`,
    DUPLICATE: (id: string) => `/groups/${id}/duplicate`,
    ARCHIVE: (id: string) => `/groups/${id}/archive`,
    UNARCHIVE: (id: string) => `/groups/${id}/unarchive`,
    PUBLIC_LINK: (id: string) => `/groups/${id}/public-link`,
    REGENERATE_LINK: (id: string) => `/groups/${id}/public-link/regenerate`,
    COLLABORATORS: (id: string) => `/groups/${id}/collaborators`,
    COLLABORATOR_BY_ID: (id: string, userId: string) => `/groups/${id}/collaborators/${userId}`,
    FAVORITE: (id: string) => `/groups/${id}/favorite`,
    PUBLIC_GROUP: (token: string) => `/groups/public/${token}`,
  },
  WORKSPACES: {
    LIST: "/workspaces",
  },
  BIN: {
    BASE: "/bin",
    RESTORE: (id: string) => `/bin/${id}/restore`,
    BY_ID: (id: string) => `/bin/${id}`,
  },
  NOTES: {
    BASE: "/notes",
    BY_ID: (id: string) => `/notes/${id}`,
    VERSIONS: (id: string) => `/notes/${id}/versions`,
    RESTORE_VERSION: (id: string, versionId: string) => `/notes/${id}/versions/${versionId}/restore`,
    FAVORITE: (id: string) => `/notes/${id}/favorite`,
    MOVE: (id: string) => `/notes/${id}/move`,
    DUPLICATE: (id: string) => `/notes/${id}/duplicate`,
    COPY: (id: string) => `/notes/${id}/copy`,
    AUTOSAVE: (id: string) => `/notes/${id}/autosave`,
    ARCHIVE: (id: string) => `/notes/${id}/archive`,
    UNARCHIVE: (id: string) => `/notes/${id}/unarchive`,
    PUBLIC_LINK: (id: string) => `/notes/${id}/public-link`,
    REGENERATE_LINK: (id: string) => `/notes/${id}/public-link/regenerate`,
    REVOKE_LINK: (id: string) => `/notes/${id}/public-link`,
    PUBLIC_NOTE: (token: string) => `/notes/public/${token}`,
  },
  ACTIVITIES: {
    ME: "/activities/me",
    ME_BY_ENTITY: (entityType: string) => `/activities/me/entity/${entityType}`,
    ME_BY_ACTION: (action: string) => `/activities/me/action/${action}`,
    ENTITY: (entityType: string, entityId: string) => `/activities/entity/${entityType}/${entityId}`,
    ME_RANGE: "/activities/me/range",
    ME_STATS: "/activities/me/stats",
  }
};
